name: CI


on: ["push", "pull_request", "workflow_dispatch"]


jobs:
  C:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: ./github/workflows/rebuild.sh

